GET http://localhost:3002/api/films
###

GET http://localhost:3002/api/films/filters/all
###

GET http://localhost:3002/api/films/filters/favorites
###

GET http://localhost:3002/api/films/filters/bestrated
###

GET http://localhost:3002/api/films/filters/seenlastmonth
###

GET http://localhost:3002/api/films/filters/unseen
###

GET http://localhost:3002/api/films/2
###

POST http://localhost:3002/api/films/insert
Content-Type: application/json

{
  "title": "Belli ciao",
  "favorite": true,
  "watchdate": "2023-05-01",
  "rating": 5,
  "user": 3
}
###

PUT http://localhost:3002/api/films/update/2
Content-Type: application/json

{
  "title": "Belli ciao",
  "favorite": true,
  "watchdate": "2023-05-10",
  "rating": 3,
  "user": 3
}
###

PUT http://localhost:3002/api/films/update/2/rating
Content-Type: application/json

{
  "rating": 3
}
###

PUT http://localhost:3002/api/films/update/2/favorite
Content-Type: application/json

{
  "favorite": false
}
###

DELETE http://localhost:3002/api/films/
###
