GET http://localhost:3002/api/films
###

GET http://localhost:3002/api/films/filters/all
###

GET http://localhost:3002/api/films/filters/favorites
###

GET http://localhost:3002/api/films/filters/bestrated
###

GET http://localhost:3002/api/films/filters/seenlastmonth
###

GET http://localhost:3002/api/films/filters/unseen
###
